/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gemabit.vhostmanager.ui;

import com.gemabit.vhostmanager.Profile;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lsoares
 */
public class Main extends javax.swing.JFrame {

    private DefaultTableModel model; 

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        model = (DefaultTableModel) tableVirtualHosts.getModel();
        addProfilesToCB(Profile.getProfiles());
        
    }
    
    private void addProfilesToCB(ArrayList<String> listOfProfiles) {
        
        Vector comboBoxItems = new Vector();
        
        for (String profileName : listOfProfiles) {
            cbbProfiles.addItem(profileName);
        }
    }

    /**
     * This method is  called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableVirtualHosts = new javax.swing.JTable();
        btnRemoveHost = new javax.swing.JButton();
        btnAddHost = new javax.swing.JButton();
        cbbProfiles = new javax.swing.JComboBox();
        btnNewProfile = new javax.swing.JButton();
        btnConnectionSettings = new javax.swing.JButton();
        btnFileSettings = new javax.swing.JButton();
        btnEditHost = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        vHostPreferencesMenu = new javax.swing.JMenuItem();
        vHostExitMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableVirtualHosts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Domain", "Alias", "Path"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableVirtualHosts);

        btnRemoveHost.setText("Remove Host");
        btnRemoveHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveHostActionPerformed(evt);
            }
        });

        btnAddHost.setText("Add Host");
        btnAddHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHostActionPerformed(evt);
            }
        });

        btnNewProfile.setText("New Profile");
        btnNewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProfileActionPerformed(evt);
            }
        });

        btnConnectionSettings.setText("Connection Settings");
        btnConnectionSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectionSettingsActionPerformed(evt);
            }
        });

        btnFileSettings.setText("File Settings");
        btnFileSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileSettingsActionPerformed(evt);
            }
        });

        btnEditHost.setText("Edit Host");
        btnEditHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditHostActionPerformed(evt);
            }
        });

        jMenu1.setText("vHost");

        vHostPreferencesMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        vHostPreferencesMenu.setText("Preferences");
        vHostPreferencesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vHostPreferencesMenuActionPerformed(evt);
            }
        });
        jMenu1.add(vHostPreferencesMenu);

        vHostExitMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        vHostExitMenu.setText("Exit");
        vHostExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vHostExitMenuActionPerformed(evt);
            }
        });
        jMenu1.add(vHostExitMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(btnEditHost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnAddHost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnRemoveHost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(cbbProfiles, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnNewProfile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnConnectionSettings, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnFileSettings, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnNewProfile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cbbProfiles)
                    .add(btnConnectionSettings, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnFileSettings, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 261, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnAddHost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnRemoveHost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnEditHost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vHostPreferencesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vHostPreferencesMenuActionPerformed
        PathConfigs pathConfigsWindow = new PathConfigs();

    }//GEN-LAST:event_vHostPreferencesMenuActionPerformed

    private void vHostExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vHostExitMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vHostExitMenuActionPerformed

    private void btnRemoveHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveHostActionPerformed
        if (tableVirtualHosts.getSelectedRow() >= 0) {
            model.removeRow(tableVirtualHosts.getSelectedRow());
            // TODO remove host from database
        }
    }//GEN-LAST:event_btnRemoveHostActionPerformed

    private void btnAddHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHostActionPerformed
        model.addRow(new Object[]{"asdsad", "asdsad", "asdsad"});
    }//GEN-LAST:event_btnAddHostActionPerformed

    private void btnNewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProfileActionPerformed
        NewProfile profileWindow = new NewProfile();
    }//GEN-LAST:event_btnNewProfileActionPerformed

    private void btnConnectionSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectionSettingsActionPerformed
        NewProfile profileWindow = new NewProfile(cbbProfiles.getSelectedIndex());
    }//GEN-LAST:event_btnConnectionSettingsActionPerformed

    private void btnFileSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileSettingsActionPerformed
        PathConfigs pathConfigWindow = new PathConfigs();
    }//GEN-LAST:event_btnFileSettingsActionPerformed

    private void btnEditHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditHostActionPerformed

    public JTable getjTable1() {
        return tableVirtualHosts;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHost;
    private javax.swing.JButton btnConnectionSettings;
    private javax.swing.JButton btnEditHost;
    private javax.swing.JButton btnFileSettings;
    private javax.swing.JButton btnNewProfile;
    private javax.swing.JButton btnRemoveHost;
    private javax.swing.JComboBox cbbProfiles;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVirtualHosts;
    private javax.swing.JMenuItem vHostExitMenu;
    private javax.swing.JMenuItem vHostPreferencesMenu;
    // End of variables declaration//GEN-END:variables
}
